[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vllm-sdsie"
version = "2.0.2"
description = "Software-Defined Stochastic Inference Engine plugin for vLLM"
authors = [{ name = "Zanno Jacklin", email = "business@zanno.se" }]
license = "Apache-2.0"
dependencies = [
    "torch",
    "triton"
]

[tool.setuptools.packages.find]
include = ["vllm_sdsie*"]
